language: go
env:
  - GO111MODULE=on
os:
  - linux
  - osx
  - windows
go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"

before_install:
  - go get -t -v ./...

script:
  - go test -v -coverprofile=coverage.txt -covermode=count -timeout 30s

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then curl -s https://codecov.io/bash > .codecov && chmod +x .codecov && ./.codecov; else bash <(curl -s https://codecov.io/bash); fi
